"""add indexes

Revision ID: 8f300c5c6553
Revises: 3aecb5ee03ef
Create Date: 2026-10-02 01:29:02.114214

"""
from collections.abc import Sequence

from alembic import op

revision: str = '8f300c5c6553'
down_revision: str | None = '3aecb5ee03ef'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_artifacts_project', 'artifacts', ['project_id'], unique=False)
    op.create_index('ix_audit_log_project', 'audit_log', ['project_id', 'created_at'], unique=False)
    op.create_index('ix_comment_attachments_comment', 'comment_attachments', ['comment_id'], unique=False)
    op.create_index('ix_comments_entity', 'comments', ['project_id', 'entity_type', 'entity_id'], unique=False)
    op.create_index('ix_meeting_files_meeting', 'meeting_files', ['meeting_id'], unique=False)
    op.create_index('ix_notifications_user', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index('ix_requirements_project', 'requirements', ['project_id'], unique=False)
    op.create_index('ix_requirements_stakeholder', 'requirements', ['stakeholder_id'], unique=False)
    op.create_index('ix_task_assignments_employee', 'task_assignments', ['employee_id', 'unassigned_at'], unique=False)
    op.create_index('ix_task_assignments_task', 'task_assignments', ['task_id'], unique=False)
    op.create_index('ix_task_attachments_task', 'task_attachments', ['task_id'], unique=False)
    op.create_index('ix_task_dependencies_depends_on', 'task_dependencies', ['depends_on_task_id'], unique=False)
    op.create_index('ix_tasks_parent', 'tasks', ['parent_task_id'], unique=False)
    op.create_index('ix_tasks_project_status', 'tasks', ['project_id', 'status'], unique=False)
    op.create_index('ix_tasks_requirement', 'tasks', ['requirement_id'], unique=False)
    op.create_index('ix_transcript_segments_meeting', 'transcript_segments', ['meeting_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transcript_segments_meeting', table_name='transcript_segments')
    op.drop_index('ix_tasks_requirement', table_name='tasks')
    op.drop_index('ix_tasks_project_status', table_name='tasks')
    op.drop_index('ix_tasks_parent', table_name='tasks')
    op.drop_index('ix_task_dependencies_depends_on', table_name='task_dependencies')
    op.drop_index('ix_task_attachments_task', table_name='task_attachments')
    op.drop_index('ix_task_assignments_task', table_name='task_assignments')
    op.drop_index('ix_task_assignments_employee', table_name='task_assignments')
    op.drop_index('ix_requirements_stakeholder', table_name='requirements')
    op.drop_index('ix_requirements_project', table_name='requirements')
    op.drop_index('ix_notifications_user', table_name='notifications')
    op.drop_index('ix_meeting_files_meeting', table_name='meeting_files')
    op.drop_index('ix_comments_entity', table_name='comments')
    op.drop_index('ix_comment_attachments_comment', table_name='comment_attachments')
    op.drop_index('ix_audit_log_project', table_name='audit_log')
    op.drop_index('ix_artifacts_project', table_name='artifacts')
    # ### end Alembic commands ###
