"""position stakeholder type details

Revision ID: d3829b21fdd0
Revises: 32fcce4aeac2
Create Date: 2026-10-06 17:06:18.698224

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'd3829b21fdd0'
down_revision: str | None = '32fcce4aeac2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('positions', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('positions', sa.Column('representatives', sa.Text(), nullable=True))
    op.add_column('positions', sa.Column('influence', sa.String(length=200), nullable=True))
    op.add_column('positions', sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'sort_order')
    op.drop_column('positions', 'influence')
    op.drop_column('positions', 'representatives')
    op.drop_column('positions', 'category')
    op.drop_column('positions', 'description')
    # ### end Alembic commands ###
